---
- name: gather facts
  setup:

- name: install cifs tools
  apt:
    name: cifs-utils
    state: present
  become: yes

- name: credentials files path
  set_fact:
    vg_mount_cred_file: ~/.vagrant-share-credentials

- name: record credentials in a file
  copy:
    content: |
      username={{ vg_share_user }}
      password={{ vg_share_pass }}
    dest: "{{ vg_mount_cred_file }}"
    owner: "{{ vg_share_uid }}"
    mode: 0600

- name: expand mount path
  set_fact:
    vg_mount_dir: "{{ vg_share_mount | expanduser }}"

- name: create mount point
  file:
    path: "{{ vg_mount_dir }}"
    state: directory
    owner: "{{ vg_share_uid }}"
    mode: 0750
  become: yes

- name: set mount options
  set_fact:
    mount_opts:
      - rw
      - noauto
      - x-systemd.automount
      - uid={{ vg_share_uid }}
      - gid={{ vg_share_gid }}
      - credentials={{ vg_mount_cred_file | expanduser }}
      - vers=2.0
      - iocharset=utf8
      - file_mode=0644
      - dir_mode=0755
      #- cache=none


- name: modify fstab
  mount:
    path: "{{ vg_mount_dir }}"
    fstype: cifs
    src: //{{ vg_share_host }}/{{ vg_share_name }}
    opts: "{{ mount_opts | join(',') }}"
    state: mounted
  become: yes
  notify: activate systemd mounts
...
