---
- name: gather facts
  setup:

- name: install cifs tools and utf8 filesystem charset
  apt:
    name:
      # systemd mounter will require /sbin/mount.cifs
      - cifs-utils
      # mounting with utf8 nls charset requires extra kernel modules
      # see:
      #   https://github.com/chef/bento/issues/804
      #   https://askubuntu.com/questions/519796/unable-to-mount-cifs-with-iocharset-utf8-in-trusty
      #   https://superuser.com/questions/682362/unicode-characters-in-ubuntu-server
      - linux-image-extra-virtual
    state: present
    # --no-install-recommends minimizes the install
    # if the problem persists, reinstall with the recommends
    install_recommends: no
  become: yes
  register: apt_result

- name: activate the utf8 fs charset kernel module (ok to fail, if no such module)
  command: /sbin/modprobe nls_utf8
  become: yes
  ignore_errors: yes
  when: apt_result is changed

- name: credentials files path
  set_fact:
    vg_mount_cred_file: ~/.vagrant-share-credentials

- name: record credentials in a file
  copy:
    content: |
      username={{ vg_share_user }}
      password={{ vg_share_pass }}
    dest: "{{ vg_mount_cred_file }}"
    owner: "{{ vg_share_uid }}"
    mode: 0600

- name: expand mount path
  set_fact:
    vg_mount_dir: "{{ vg_share_mount | expanduser }}"

- name: create mount point
  file:
    path: "{{ vg_mount_dir }}"
    state: directory
    owner: "{{ vg_share_uid }}"
    mode: 0750
  become: yes

- name: set mount options
  set_fact:
    mount_opts:
      - rw
      - noauto
      - x-systemd.automount
      - uid={{ vg_share_uid }}
      - gid={{ vg_share_gid }}
      - credentials={{ vg_mount_cred_file | expanduser }}
      - vers=2.0
      - iocharset=utf8
      - file_mode=0644
      - dir_mode=0755
      #- cache=none


- name: modify fstab
  mount:
    path: "{{ vg_mount_dir }}"
    fstype: cifs
    src: //{{ vg_share_host }}/{{ vg_share_name }}
    opts: "{{ mount_opts | join(',') }}"
    # we don't need "mounted" because we setup automount
    state: present
  become: yes
  notify: activate systemd mounts
...
