---
# handlers file for vagrant-share

- name: activate systemd mounts
  systemd:
    name: remote-fs.target
    state: restarted
    daemon_reload: yes
  become: yes
  # expected error: "path is already a mount point, refusing start"
  ignore_errors: yes
...
